# Generated by Django 5.1.1 on 2024-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('President', 'Student President'), ('Secretary', 'Secretary'), ('Student', 'Student'), ('Leader', 'Cohort Leader'), ('Vice', 'Vice Student President')], default='Student', max_length=9),
        ),
    ]
