# Generated by Django 5.1.1 on 2024-11-11 10:51

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[students.models.mail_validator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Secretary', 'Secretary'), ('Leader', 'Cohort Leader'), ('Vice', 'Vice Student President'), ('Student', 'Student'), ('President', 'Student President')], default='Student', max_length=9),
        ),
    ]
