# Generated by Django 5.1.1 on 2024-11-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_email_alter_student_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Secretary', 'Secretary'), ('President', 'Student President'), ('Vice', 'Vice Student President'), ('Leader', 'Cohort Leader')], default='Student', max_length=9),
        ),
    ]
