# Generated by Django 5.1.1 on 2024-11-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_slug_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Leader', 'Cohort Leader'), ('Secretary', 'Secretary'), ('Vice', 'Vice Student President'), ('President', 'Student President'), ('Student', 'Student')], default='Student', max_length=9),
        ),
    ]
