# Generated by Django 5.1.1 on 2024-11-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Secretary', 'Secretary'), ('President', 'Student President'), ('Vice', 'Vice Student President'), ('Student', 'Student'), ('Leader', 'Cohort Leader')], default='Student', max_length=9),
        ),
    ]
