# Generated by Django 5.1.1 on 2024-11-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Leader', 'Cohort Leader'), ('President', 'Student President'), ('Vice', 'Vice Student President'), ('Secretary', 'Secretary')], default='Student', max_length=9),
        ),
    ]
