# Generated by Django 5.1.1 on 2024-11-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Student', 'Student'), ('President', 'President'), ('Leader', 'Cohort Leader'), ('Vice', 'Vice President'), ('Secretary', 'Secretary')], default='Student', max_length=9),
        ),
    ]
