# Generated by Django 5.1.1 on 2024-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_phone_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('President', 'President'), ('Vice', 'Vice President'), ('Student', 'Student'), ('Leader', 'Cohort Leader'), ('Secretary', 'Secretary')], default='Student', max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
