# Generated by Django 5.1.1 on 2024-12-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Vice', 'Vice President'), ('Secretary', 'Secretary'), ('President', 'President'), ('Student', 'Student'), ('Leader', 'Cohort Leader')], default='Student', max_length=9),
        ),
    ]
